server:
  port: 8888
spring:
  application:
    name: eureka-server
eureka:
  client:
    #�Ƿ�ע���Լ�����Ϣ��EurekaServer,Ĭ��true
    register-with-eureka: false
    #�Ƿ���ȡ�����������Ϣ�� Ĭ����true
    fetch-registry: false
    # EurekaServer�ĵ�ַ���������Լ��ĵ�ַ������Ǽ�Ⱥ����Ҫ��������Server�ĵ�ַ��
    service-url:
      defaultZone: http://192.168.31.77:${server.port}/eureka/
